const labels = require('./packages');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const packageConfigs = {};

labels.forEach(({ id }) => {
  packageConfigs[id] = [{ type: 'autogenerated', dirName: `api/${id}` }];
});

const sidebars = {
  tutorial: [{ type: 'autogenerated', dirName: 'tutorial' }],
  api: labels.map(({ id, label }) => ({
    type: 'html',
    value: `<a class="recative-package menu__link" href="/docs/api/${id}">${label}</a>`,
  })),
  ...packageConfigs,
};

module.exports = sidebars;
