/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  technotes: [{ type: 'autogenerated', dirName: 'technotes' }],
  studio: [{ type: 'autogenerated', dirName: 'studio' }],
};

module.exports = sidebars;
