// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorial: [{ type: 'autogenerated', dirName: 'tutorial' }],
  api: [{ type: 'autogenerated', dirName: 'api' }],
};

module.exports = sidebars;
